---
- hosts: all
  become: true
  tasks:
    - name: Add ethereum ppa
      apt_repository:
        repo: ppa:ethereum/ethereum

    - name: Add ethereum-dev ppa
      apt_repository:
        repo: ppa:ethereum/ethereum-dev

    - name: Add ethereum libs ppa
      apt_repository:
        repo: ppa:ethereum/cpp-build-deps

    - name: Apt update
      apt: update_cache=yes

    - name: Download setup_10.x
      get_url: url=https://deb.nodesource.com/setup_10.x dest=/tmp/setup_10.x

    - name: Add execute permissions to setup_10.x
      file:
        path: /tmp/setup_10.x
        mode: '0744'

    - name: Execute setup_10.x
      shell: /tmp/setup_10.x

    - name: Install depends
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - net-tools
        - build-essential
        - solc
        - ethereum
        - nginx
        - curl
        - vim
        - nodejs
        - python3-pip
        - ruby-full
        - docker.io

    - name: Install ganache-cli
      community.general.npm:
        name: ganache-cli
        global: yes

    - name: Install truffle
      community.general.npm:
        name: truffle
        global: yes

    - name: Delete project directory
      file:
        path: /home/vagrant/ethereum
        state: absent

    - name: Create project directory
      file:
        path: /home/vagrant/ethereum
        state: directory

    - name: Create truffle project
      command: truffle init /home/vagrant/ethereum --force

    - name: Install web3
      command: pip3 install web3

    - name: Get kubectl
      get_url: url=https://storage.googleapis.com/kubernetes-release/release/v1.20.1/bin/linux/amd64/kubectl dest=/tmp/kubectl

    - name: Add execute permissions to kubectl
      file:
        path: /tmp/kubectl
        mode: '0755'

    - name: Move kubectl to path
      command: mv /tmp/kubectl /usr/local/bin/kubectl

    - name: Get minikube
      get_url: url=https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 dest=/tmp/minikube

    - name: Add execute permissions to minikube
      file:
        path: /tmp/minikube
        mode: '0755'

    - name: Move minikube to path
      command: mv /tmp/minikube /usr/local/bin/minikube
