---
- hosts: all
  become: true
  tasks:
    - name: update apt
      apt: update_cache=yes

    - name: install depends
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - net-tools
      